services:
  grafana:
    image: grafana/grafana
    container_name: grafana_metric
    links:
      - influxdb:influxdb_metric
    environment:
      - GF_SECURITY_ADMIN_USER= admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"
    volumes_from:
      - grafana_storage
    restart: always
  
  grafana_storage:
    image: busybox:latest
    volumes:
      - /var/lib/grafana
      - /var/log/grafana

  influxdb:
    image: tutum/influxdb:latest
    container_name: influxdb_metric
    environment:
      - ADMIN_USER=root
      - PRE_CREATE_DB=server_metric
      - INFLUXDB_INIT_PWD=root
    links:
      - aggregator_metric
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes_from:
      - influxdb_storage
    restart: always

  influxdb_storage:
    image: influxdb:latest
    volumes:
      - /opt/data

  aggregator:
    build: ./aggregator
    image: aggregator:latest
    container_name: aggregator_metric
    ports:
      - "7000:7000"
    restart: always
