grafana:
  image: matisq/grafana:latest
  container_name: grafana_metric
  links:
    - influxdb:influx
  environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=secret
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=server_metric
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root
    - INFLUXDB_IS_GRAFANADB=true
  ports:
    - "3000:3000"
  volumes_from:
    - grafana_storage
  restart: always

grafana_storage:
  image: busybox
  tty: true
  volumes:
    - /var/lib/grafana
    - /var/log/grafana

influxdb:
  image: tutum/influxdb:latest
  container_name: influxdb
  hostname: influx
  ports:
    - "8083:8083"
    - "8086:8086"
  environment:
    - ADMIN_USER=root
    - INFLUXDB_INIT_PWD=root
    - PRE_CREATE_DB=server_metric
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root
  volumes_from:
    - influxdb_storage
  restart: always

influxdb_storage:
  image: influxdb:latest
  volumes:
    - /opt/data

aggregator:
  build: aggregator
  container_name: aggregator_metric
  ports:
    - "8125:8125/udp"
    - "8092:8092/udp"
    - "8094:8094"
  links:
    - influxdb:influx
  environment:
    HOST_NAME: "telegraf"
    INFLUXDB_HOST: "influx"
    INFLUXDB_PORT: "8086"
    DATABASE: "server_metric"
  tty: true
  volumes:
    - /proc:/mnt/proc:ro
  privileged: true
  restart: always
